# Generated by Django 3.1.6 on 2021-02-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('dateofbirth', models.CharField(max_length=100)),
                ('emailAddress', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('resident', models.BooleanField(default=False)),
                ('epipenUser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VaccCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('havevaccine', models.BooleanField(default=False)),
            ],
        ),
    ]
